### ISSUE TITLE
Add JSX dependencies in documentation

### ISSUE THREAD

**Issue by purepear** [matfish2/vue-form-2#1]
Thanks for migrating to Vue 2

I tried to use this with vueify but got error and noticed that you use jsx.. so i had to install aswell https://github.com/vuejs/babel-plugin-transform-vue-jsx

It would be helpful if you mention it in https://matfish2.gitbooks.io/vue-form-2/content/

**Comment by matfish2** [comment]
I mention it in the `Installation` chapter, including a link to the transform:

Compile the code using a module bundler such as browserify or webpack, and babel-plugin-transform-vue-jsx

I'll add it to the readme file itself to make it clearer.
