### ISSUE TITLE
Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by dflock** [matfish2/vue-form-2#12]
I've followed the instructions [here](https://matfish2.gitbooks.io/vue-form-2/content/installation.html) to add `vue-form-2` to my project, but I get the following error on page load, as soon as I include `import VueForm from 'vue-form-2'` into my `main.js` file:

```
Uncaught SyntaxError: Unexpected token import
    at Object.<anonymous> (app.js:1446)
    at __webpack_require__ (app.js:556)
    at fn (app.js:87)
    at eval (eval at <anonymous> (app.js:948), <anonymous>:11:16)
    at Object.<anonymous> (app.js:948)
    at __webpack_require__ (app.js:556)
    at fn (app.js:87)
    at Object.<anonymous> (app.js:587)
    at __webpack_require__ (app.js:556)
    at app.js:579
```

Here are the relevant sections of my config files:

### .babelrc

```
{
  "presets": ["es2015", "stage-2"],
  "plugins": ["transform-runtime", "transform-vue-jsx"],
  "comments": false
}
```

### package.json

```
...
"dependencies": {
    "vue": "^2.1.0",
    "vue-form-2": "^0.1.54"
  },
  "devDependencies": {
    "babel-core": "^6",
    "babel-helper-vue-jsx-merge-props": "^2",
    "babel-loader": "^6",
    "babel-plugin-syntax-jsx": "^6",
    "babel-plugin-transform-runtime": "^6",
    "babel-plugin-transform-vue-jsx": "^3",
    "babel-preset-es2015": "^6",
    "babel-preset-stage-2": "^6",
...
```

### webpack.base.conf.js

```
...
  module: {
    loaders: [
      {
        test: /\.js$/,
        loader: 'babel',
        include: projectRoot,
        exclude: /node_modules/
      },
...
```

Is there any more information that would help in figuring this out?

**Comment by matfish2** [comment]
Please paste your `main.js` file
Also, your webpack config is incorrect. I've added the correct setup to the README file

**Comment by dflock** [comment]
Relevant section from `main.js` was just this:

```js
import VueForm from 'vue-form-2'

Vue.use(VueForm)
```

I've added the `jsx` loader from the README to my `webpack.base.conf` and it's working now, thanks!

**Comment by xibman** [comment]
Hi matfish2,
I have the same problem Unexpected token import,

I use jsx loader you provide in conf but i have the same error but it refer to import merge from 'merge' form your index.js

**Comment by matfish2** [comment]
@xibman, `Unexpected token import` means that the compiler doesn't recognize ES2015 syntax. Check you `.babelrc` and make sure it loads the ES2015 preset.

**Comment by xibman** [comment]
my .babelrc:
`{
  "presets": ["es2015", "stage-2"],
  "comments": false,
  "env": {
    "test": {
      "plugins": [ "istanbul" ]
    }
  }
}`

**Comment by xibman** [comment]
@matfish2 I think the problems come from windows node version or windows, because on linux no problem !
