### ISSUE TITLE
Update curValue through value property

### ISSUE THREAD

**Issue by c0defre4k** [matfish2/vue-form-2#15]
In my current setup I use a form for creating and updating records. For this case I assign the values via the value property. The problem is that the input value isn't updated.

Is there already a proper way to do this, otherwise I would prepare a pull-request with a watcher with an additional watcher for updating the curValue when the props value has changed.

**Comment by matfish2** [comment]
Props in vue 2 are immutable, that is, you are not supposed to change them directly. Also, the `value` prop is only used to set the *initial* value. To programmatically set a value use the `setValue()` method on the field.

**Comment by c0defre4k** [comment]
My idea was actually to use the ``value`` prop to change the values when switching between records.

E.g. I have some sort of list and detail view. Both views are kept in memory with Vue's ``keep-alive`` to keep the state of the list. The selected record is always passed as prop to my form component. Now it would be really convenient if i could just update the selected record and let Vue do its job propagating the changes. Calling ``setValue()`` on each form field would be pretty cumbersome.
Another example is, when I switch routes from one record to another.
