### ISSUE TITLE
Error when rendering vf-date

### ISSUE THREAD

**Issue by c0defre4k** [matfish2/vue-form-2#2]
I get the following errors when trying to use the datepicker input:

```
[Vue warn]: Error when rendering component <vf-date>
Uncaught TypeError: Cannot read property 'apply' of undefined
Uncaught TypeError: Cannot read property 'setStartDate' of undefined
```

Datepicker is installed. This is my template for the input: 

```
<vf-date :label="$t('participant.birthday')" name="birthday" :value="moment(participant.birthday)"></vf-date>
```

The moment method is just a proxy to moment and the date is in the format YYYY-MM-DD.

Can you please provider a demo form with all inputs?

**Comment by matfish2** [comment]
I don't see any problem with your code. Please provide the versions you are working with (vue, jquery, moment, daterangepicker)
I can't provide a demo because I don't have a precompiled version to reference in my fiddle. In addition, I believe the documentation is clear enough.

**Comment by c0defre4k** [comment]
These are my versions:
jQuery: 3.1.1,
Vue: 2.0.3,
moment: 2.15.2,
daterangepicker: 2.1.24

**Comment by matfish2** [comment]
Using those exact versions I was unable to reproduce the issue.
For debugging purposes, please remove possible confounding factors and try again, I.e use a simple string `label` and no `value` at all.

**Comment by c0defre4k** [comment]
I made a simple fiddle: https://jsfiddle.net/cczo0auk/3/

**Comment by matfish2** [comment]
The problem lies in line 10818:

`}, [_dates2.default[this.type].apply(this, [h])]`

For some reason in your compiled file `dates2` has two nested `default` objects, instead of one in mine.
I've tried to fix it by avoiding `export default` on `dates.js`. 
Please try again.

**Comment by c0defre4k** [comment]
Thanks! Your fix solved the problem.
