### ISSUE TITLE
this.$root vs this.$parent

### ISSUE THREAD

**Issue by purepear** [matfish2/vue-form-2#5]
I'm migrating a project to Vue2

my form begins with this (I'm using Jade/Pug)
```jade
vf-form(v-if="!isLoading", method="POST", ajax, :action="apiUrl", :validation="validation", :options="options")
  vf-status-bar(ref="statusbar")

```
when submitting i got an error `Cannot read property 'info' of undefined(…)`
This is because the ajax submitter is trying to get the status bar `let status =  vm.getStatusBar();` 
The status bar get method is 
```javascript
module.exports = function() {
  return this.$root.$refs.statusbar;
}
```

I changed it to `return this.$parent.$refs.statusbar` and it worked
I think the $root element refers to the top most element which does not hold the vf-status-bar element 

I did a search in all the source and found other `this.$root...` mentions... i'm wondering should they be changed to `this.$parent...` too?

**Comment by matfish2** [comment]
Merged PR #4
