### ISSUE TITLE
Is it possible to change field value by changing this.data

### ISSUE THREAD

**Issue by purepear** [matfish2/vue-form-2#6]
```
vf-text(label="Price", name="price", :value="record.price", ref="price")
```
Changing `this.record.price = 123` in a method doesn't change the value of the input

Tried also `v-model` without success

**Comment by matfish2** [comment]
The initial value, be it a variable, is not bound to the `curValue` property.
Setting a new value is done either through the form or through explicit programmatic manipulation (`setValue(x)`).
